FROM node:alpine
# Create and set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY shipping-frontend/package*.json ./

RUN npm install -g @angular/cli

RUN npm install

# Copy the source code to the working directory
COPY shipping-frontend/. .

CMD ["ng", "serve", "--host", "0.0.0.0"]