version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: shipping_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      POSTGRES_DB: shipping_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
    depends_on:
      - postgres
    ports:
      - "3000:3000"
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "4200:4200"
