FROM node:alpine

# Create and set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY shipping-backend/package*.json ./

# Install project dependencies
RUN npm install

# Copy the source code to the working directory
COPY shipping-backend/. .

# Build the NestJS application
RUN npm run build

# Expose the port that the application will run on
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "start:prod"]
